version: '3.9'

services:
  format_db_host:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - format_db_host
    env_file:
      - .env
    ports:
      - "8062:8062"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8062"]

volumes:
  db_data:
